In [1]:
import numpy as np
arr=np.arange(14,24)
print(arr,arr[8])
print(arr[1:4],arr[:3]) #we use to slice array
# broadcast 
arr[:4]=100
copy_arr=arr[:8] #this will not create a new one instead create a pointer.
cp_arr=arr.copy()
print(arr)
arr[:]=00
print(arr,copy_arr,cp_arr)

[14 15 16 17 18 19 20 21 22 23] 22
[15 16 17] [14 15 16]
[100 100 100 100  18  19  20  21  22  23]
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0] [100 100 100 100  18  19  20  21  22  23]


In [2]:
arr=np.random.randint(1,100,16)
arr=arr.reshape(4,4) #converted an array into a matrix of 3x3
print(arr,arr.shape,arr.reshape(2,8))
print(arr[1,2],arr[3][2]) # by these two way we can access an element of arr.
# how to copy or slice a part of matrix ,and assign to a variable?
print(arr[:2,1:]) # it exclude upper limit.(:2) means from 0 to 1.
print(arr[:,:1]) #this print colmn 1.

[[12 66 46  3]
 [24 85 69 77]
 [48 44 69 67]
 [85 89 63 13]] (4, 4) [[12 66 46  3 24 85 69 77]
 [48 44 69 67 85 89 63 13]]
69 63
[[66 46  3]
 [85 69 77]]
[[12]
 [24]
 [48]
 [85]]


In [3]:
boolean_m=arr>29
print(boolean_m)
print(arr[boolean_m])# it create an array of element satisied the condition.
print(arr[arr>45]) #conditional selection.

[[False  True  True False]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]]
[66 46 85 69 77 48 44 69 67 85 89 63]
[66 46 85 69 77 48 69 67 85 89 63]


In [4]:
arr=np.arange(4,34,3)
print(arr)
print(arr+5,arr-3)
print(arr*arr,arr-arr)
# if we divide with zero then it gives warning with print with nan in numy
# without numpy it gives error istead of warning
print(np.sqrt(45))
print(np.sin(arr))
print(np.sum(arr))
print(arr.sum(),arr.max(),arr.min(),arr.var(),arr.std())


[ 4  7 10 13 16 19 22 25 28 31]
[ 9 12 15 18 21 24 27 30 33 36] [ 1  4  7 10 13 16 19 22 25 28]
[ 16  49 100 169 256 361 484 625 784 961] [0 0 0 0 0 0 0 0 0 0]
6.708203932499369
[-0.7568025   0.6569866  -0.54402111  0.42016704 -0.28790332  0.14987721
 -0.00885131 -0.13235175  0.27090579 -0.40403765]
175
175 31 4 74.25 8.616843969807043


In [6]:
arr=(np.arange(0,25).reshape(5,5))
print(arr)
print(arr.sum(axis=0),arr.sum(axis=1)) 
# axis =0 means sum of all rows columnwise other word sum of each column
# axis=1 means sum of all rows

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[50 55 60 65 70] [ 10  35  60  85 110]
